name: Flutter Android CI

on:
  push:
    branches:
    - main
    - master
    - release/*

jobs: 
  build:
    runs-on: "ubuntu-latest"
    steps: 
        - uses: subosito/flutter-action@v2.14.0
          with: 
            flutter-version: '3.29.3'
            channel: 'stable'
            
        - uses: actions/checkout@v5.0.0

        - name: Build Release APK
          run: flutter build apk

        - name: Upload APK
          uses: actions/upload-artifact@v4.6.2
          with:
            name: flutter-apk
            path: build/app/outputs/flutter-apk/app-release.apk
        - name: List build folder
          run: ls -R build/app/outputs/flutter-apk/

        - name: Install gdrive CLI
          run: |
           sudo apt-get install unzip
           curl -L -o gdrive.zip https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive-linux-x64
           chmod +x gdrive-linux-x64
           sudo mv gdrive-linux-x64 /usr/local/bin/gdrive
        - name: Upload to Google Drive
          env:
            GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          run: |
            echo "$GDRIVE_SERVICE_ACCOUNT" > sa.json
            gdrive --service-account sa.json upload build/app/outputs/flutter-apk/app-release.apk

       
          
