name: Flutter Android CI

on:
  push:
    branches:
    - main
    - master
    - release/*

jobs: 
  build:
    runs-on: "ubuntu-latest"
    steps: 
        - uses: subosito/flutter-action@v2.14.0
          with: 
            flutter-version: '3.29.3'
            channel: 'stable'
            
        - uses: actions/checkout@v5.0.0

        - name: Build Release APK
          run: flutter build apk

        - name: Upload APK
          uses: actions/upload-artifact@v4.6.2
          with:
            name: flutter-apk
            path: build/app/outputs/flutter-apk/app-release.apk

       
          
